### ISSUE TITLE
please make deploy to heroku button

### ISSUE THREAD

**Issue by raisedhand** [intrlocutr/nightcoreify#5]
Hi Thomas ,
please if it's possible make deploy to heroku button for free of monthly vps charge. also youtube have any buildpack you need like selenium , chrome headless , ffmpeg or ...
waiting for your response
finest regards

**Comment by intrlocutr** [comment]
I have experimented with Heroku in the past but I had a ton of trouble getting ffmpeg to work with it. Additionally, Heroku isn't really designed for this type of use case, they want more traditional web "apps" and not arbitrarily invoked functions (though mine isn't technically arbitrarily invoked since it's on a schedule). To your second question, this script doesn't require anything like Selenium or headless Chromium--the only thing close to that, and this doesn't even come remotely close, is youtube-dl is effectively a scraper for YouTube's website, but that's all handled by youtube-dl itself, you don't have to worry about that when using its API or calling it from CLI.
